/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Day: typeof import('./src/components/shared/s-calendar/day.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SAvatar: typeof import('./src/components/shared/s-avatar.vue')['default']
    SButton: typeof import('./src/components/shared/s-button.vue')['default']
    SCalendar: typeof import('./src/components/shared/s-calendar/index.vue')['default']
    SCalendarDateIndicator: typeof import('./src/components/shared/s-calendar/s-calendar-date-indicator.vue')['default']
    SCalendarDateSelector: typeof import('./src/components/shared/s-calendar/s-calendar-date-selector.vue')['default']
    SCalendarMonth: typeof import('./src/components/shared/s-calendar/s-calendar-month.vue')['default']
    SCalendarMonthDayItem: typeof import('./src/components/shared/s-calendar/s-calendar-month-day-item.vue')['default']
    SCalendarWeekdays: typeof import('./src/components/shared/s-calendar/s-calendar-weekdays.vue')['default']
    SCard: typeof import('./src/components/shared/s-card.vue')['default']
    SDialog: typeof import('./src/components/shared/s-dialog.vue')['default']
    SIcon: typeof import('./src/components/shared/s-icon.vue')['default']
    SInput: typeof import('./src/components/shared/s-input.vue')['default']
    SSelect: typeof import('./src/components/shared/s-select.vue')['default']
    STable: typeof import('./src/components/shared/s-table/index.vue')['default']
    Weekdays: typeof import('./src/components/shared/s-calendar/weekdays.vue')['default']
  }
}
