/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SAvatar: typeof import('./src/components/shared/s-avatar.vue')['default']
    SButton: typeof import('./src/components/shared/s-button.vue')['default']
    SCard: typeof import('./src/components/shared/s-card.vue')['default']
    SIcon: typeof import('./src/components/shared/s-icon.vue')['default']
    SInput: typeof import('./src/components/shared/s-input.vue')['default']
  }
}
